version: "3.7"
services:
  web:
    image: IMAGE_NAME:$TAG_IMAGE
    container_name: CONTAINER_NAME
    build:
      context: Dockerfile
      target: $ENV
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - ${PORT}:80
    environment:
      REACT_APP_API_URL: ${!REACT_APP_API_URL}
      REACT_APP_API_KEY: ${!REACT_APP_API_KEY}
